development: &default
  adapter: postgresql
  encoding: unicode
  database: omgtodos_development
  pool: 5
  username: postgres
  password: postgres
  min_messages: warning

test:
  <<: *default
  database: omgtodos_test
  
production:
  <<: *default
  database: omgtodos_production
